const express = require('express')
const app = express()
const port = 3000


// get store
app.get('/getStore', (req, res) => {

    
 const data = [ {StoreName:"Nyem Nyem Pengasih",StoreCategory:"Food and Beverages",StoreAddress:"Jl. KRT Kertodiningrat, Karang Tengah Kidul, Margosari, Kec. Pengasih, Kabupaten Kulon Progo, Daerah Istimewa Yogyakarta 55652, Indonesia"},
{StoreName:"AYAM GEPREK NAMPOL HAJI TEN",StoreCategory:"Food and Beverages",StoreAddress:"Jl. H. Ten III No.22, RT.9/RW.1, Rawamangun, Kec. Pulo Gadung, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13220, Indonesia"},
{StoreName:"SKR Dumai ",StoreCategory:"Food and Beverages",StoreAddress:"Jl. Sultan Hasanuddin No.28, Rimba Sekampung, Dumai Bar., Kota Dumai, Riau 28826, Indonesia"},
{StoreName:"NaGhi Store",StoreCategory:"Fashion and Accessories",StoreAddress:"Jl. Raya Kalumata Puncak, Kalumata, Ternate Sel., Kota Ternate, Maluku Utara, Indonesia"},
{StoreName:"mitra jaya sembako",StoreCategory:"Minimarket",StoreAddress:"Jl. Cibaraja No.14, Selajambe, Kec. Cisaat, Sukabumi Regency, Jawa Barat 43152, Indonesia"},
{StoreName:"julian store",StoreCategory:"Fashion and Accessories",StoreAddress:"Jl. Ir. H. Juanda, Tamansari, Kec. Bandung Wetan, Kota Bandung, Jawa Barat 40116, Indonesia"},
{StoreName:"goedangsehat.com",StoreCategory:"Food and Beverages",StoreAddress:"Bandung, Kota Bandung, Jawa Barat, Indonesia"},
{StoreName:"Aditya store",StoreCategory:"Fashion and Accessories",StoreAddress:"Jl. Panglima Polem No.39, Gampong Jawa, Langsa Kota, Kota Langsa, Aceh 24375, Indonesia"},
{StoreName:"Al-adeeva store",StoreCategory:"Minimarket",StoreAddress:"Villa kencana cikarang"},
{StoreName:"rafania collection",StoreCategory:"Fashion and Accessories",StoreAddress:"Gg. H. Nawi No.12 B, RT.10/RW.8, Pd. Pinang, Kec. Kby. Lama, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12310, Indonesia"},
{StoreName:"Pelangi Official Store",StoreCategory:"Food and Beverages",StoreAddress:"Jl. Pandawa 15 No.3, Karangsatria, Kec. Tambun Utara, Bekasi, Jawa Barat 17510, Indonesia"},
{StoreName:"Warung Mencrang",StoreCategory:"Food and Beverages",StoreAddress:""},
{StoreName:" MAXIM FOOD",StoreCategory:"Fashion and Accessories",StoreAddress:"Jl. R.Dengklok, Kertarahayu, Cibuaya, Kabupaten Karawang, Jawa Barat 41356, Indonesia"},
{StoreName:"SYAFAAH STORE",StoreCategory:"Fashion and Accessories",StoreAddress:"Jl. Raya Sudirman No.117, Tekoan, Tanggul Kulon, Kec. Tanggul, Kabupaten Jember, Jawa Timur 68155, Indonesia"},
{StoreName:"azza collection",StoreCategory:"Fashion and Accessories",StoreAddress:"Dusun Soto, Desa Sidodadi, Kecamatan Bangilan, Kabupaten Tuban, Soto, Sidodadi, Bangilan, Kabupaten Tuban, Jawa Timur 62364, Indonesia"},
{StoreName:"NIKEN DRAVERS SAIYAN STORE",StoreCategory:"Fashion and Accessories",StoreAddress:"Gg. CC Jl. Kemanggisan Pulo No.30, RT.6/RW.9, Palmerah, Kec. Palmerah, Kota Jakarta Barat, Daerah Khusus Ibukota Jakarta 11480, Indonesia"},
{StoreName:"Darwien Shop",StoreCategory:"Fashion and Accessories",StoreAddress:"Mranggen, Kabupaten Demak, Jawa Tengah 59567, Indonesia"},
{StoreName:"Bakpia Jogja Dan aneka cemilan",StoreCategory:"Food and Beverages",StoreAddress:"Gg. Manggis 2 No.122, Bengkong Indah, Kec. Bengkong, Kota Batam, Kepulauan Riau 29444, Indonesia"},
{StoreName:"Biomart",StoreCategory:"Food and Beverages",StoreAddress:""},
{StoreName:"Oemah ZIdA",StoreCategory:"Food and Beverages",StoreAddress:"Jl. Bumi Godean I No.35, Sarimulyo, Tawangsari, Kec. Wonosobo, Kabupaten Wonosobo, Jawa Tengah 56314, Indonesia"},
{StoreName:"maxim ",StoreCategory:"Food and Beverages",StoreAddress:"Jl. R.Dengklok, Cibuaya, Kabupaten Karawang, Jawa Barat 41356, Indonesia"},
{StoreName:"FRIET'S Gallery",StoreCategory:"Fashion and Accessories",StoreAddress:"Lubuk Kebur, Kec. Seluma, Kabupaten Seluma, Bengkulu, Indonesia"},
{StoreName:"Toko Ratoe",StoreCategory:"Fashion and Accessories",StoreAddress:"Jl. Purnawirawan Raya No.6, Gedong Meneng Kota Bandar Lampung, Lampung 35113, Indonesia"},
{StoreName:"Alverva.co",StoreCategory:"Beauty & Health",StoreAddress:"Jl. Raya Parakan - Wonosobo, Kwadungan Jurang, Kec. Kledung, Kabupaten Temanggung, Jawa Tengah 56264, Indonesia"},
{StoreName:"Es Goceng 88",StoreCategory:"Food and Beverages",StoreAddress:"91922, Jl. Nanakan No.21, Amasangan, Wara, Kota Palopo, Sulawesi Selatan 91911, Indonesia"},
{StoreName:"GaLeri19antik",StoreCategory:"Fashion and Accessories",StoreAddress:"Lorong Kedemangan, 7 Ulu, Kecamatan Seberang Ulu I, Kota Palembang, Sumatera Selatan, Indonesia"},
{StoreName:"heldaolshop",StoreCategory:"Fashion and Accessories",StoreAddress:"Indonesia"},
{StoreName:"Alex's Collection's",StoreCategory:"Fashion and Accessories",StoreAddress:"DKI Jakarta"},
{StoreName:"MARKET EL -MAEJIZ",StoreCategory:"Fashion and Accessories",StoreAddress:"kuningan"},
{StoreName:"Binar Fashion",StoreCategory:"Fashion and Accessories",StoreAddress:"Kebonsari II"},
{StoreName:"BAJU MURAH PALEMBANG",StoreCategory:"Fashion and Accessories",StoreAddress:"Lrg. Harapan No.915, 13 Ulu, Kec. Seberang Ulu II, Kota Palembang, Sumatera Selatan 30115, Indonesia"},
{StoreName:"LIQUORSHOP88",StoreCategory:"Food and Beverages",StoreAddress:"Dasana Puri Utama No.1, RT.7/RW.8, Duri Kosambi, Kecamatan Cengkareng, Kota Jakarta Barat, Daerah Khusus Ibukota Jakarta 11750, Indonesia"},
{StoreName:"PHBI Mart",StoreCategory:"Minimarket",StoreAddress:"Jl. Rambutan 3 No.E-529, Tambaksumur, Wadungasri, Kec. Waru, Kabupaten Sidoarjo, Jawa Timur 61256, Indonesia"},
{StoreName:"AGEN GROSIR KERIPIK BUAH Dan OLEH OLEH KHAS MALANG",StoreCategory:"Minimarket",StoreAddress:"Jl. Raya Pakis Kembar No.285, Ngerangin, Sumberpasir, Kec. Pakis, Malang, Jawa Timur 65154, Indonesia"},
{StoreName:"Brisca",StoreCategory:"Minimarket",StoreAddress:"Unnamed Road, Bubakan, Kec. Mijen, Kota Semarang, Jawa Tengah 50216, Indonesia"},
{StoreName:"D'FOUR RRAS STORE",StoreCategory:"Fashion and Accessories",StoreAddress:"Unnamed Road, Waru, Parung, Bogor, Jawa Barat 16330, Indonesia"},
{StoreName:"Y&A (Yayah & Andi ) Kuliner Majalengka",StoreCategory:"Food and Beverages",StoreAddress:"Jl. Ahmad Yani No.1, Majalengka Kulon, Kec. Majalengka, Kabupaten Majalengka, Jawa Barat 45418, Indonesia"},
{StoreName:"ROSE ðŸŒ¹ Mart ",StoreCategory:"Minimarket",StoreAddress:"Grand Rose Regency B-27 Kemiri, Kec. Sidoarjo, Kabupaten Sidoarjo, Jawa Timur 61234, Indonesia"},
{StoreName:"tepung kentaky",StoreCategory:"Food and Beverages",StoreAddress:"perum taman adidharma,desa gunung jati,cirebon utara"},
{StoreName:"INDAH GROSIR",StoreCategory:"Fashion and Accessories",StoreAddress:"Unnamed Road, Somor Dalem, Juruan Laok, Batuputih, Kabupaten Sumenep, Jawa Timur 69453, Indonesia"},
{StoreName:"SOPPI.ID",StoreCategory:"Fashion and Accessories",StoreAddress:"jl. zaenal sakse no 11 "},
{StoreName:"Zahra Afy Colection",StoreCategory:"Fashion and Accessories",StoreAddress:"Gg. Jembar II No.2, Parakan, Ciomas, Bogor, Jawa Barat 16610, Indonesia"},
{StoreName:"Distributor Hwi Uka",StoreCategory:"Beauty & Health",StoreAddress:"Jl.komp. Uka Blok BB No:04 Rt:011Rw : 008, RT.10/RW.8, Tugu Utara, Kec. Koja, Kota Jkt Utara, Daerah Khusus Ibukota Jakarta 14260, Indonesia"},
{StoreName:"Zahra faceshop",StoreCategory:"Fashion and Accessories",StoreAddress:""},
{StoreName:"Scarlett Whitening",StoreCategory:"Beauty & Health",StoreAddress:"Jl. Bangau No.58a, 9 Ilir, Kec. Ilir Tim. II, Kota Palembang, Sumatera Selatan 30114, Indonesia"},
{StoreName:"TOKO AZZAHRA ACCESSORIES",StoreCategory:"Minimarket",StoreAddress:"Kp. Belendung, Kedung Pengawas, Kec. Babelan, Bekasi, Jawa Barat 17610, Indonesia"},
{StoreName:"pasar basah",StoreCategory:"Food and Beverages",StoreAddress:"Jl. Nusantara No.43a, Calaca, Kec. Wenang, Kota Manado, Sulawesi Utara, Indonesia"},
{StoreName:"Hann Olshop Kediri",StoreCategory:"Fashion and Accessories",StoreAddress:"Unnamed Road, Area Sawah, Pandantoyo, Ngancar, Kediri, Jawa Timur 64291, Indonesia"},
{StoreName:"Bi'Store",StoreCategory:"Food and Beverages",StoreAddress:"Jalan Duri Raya Masjid Al Uchwah II No.24, Kedoya, RT.13/RW.1, Kedoya Sel., Kec. Kb. Jeruk, Kota Jakarta Barat, Daerah Khusus Ibukota Jakarta 11520, Indonesia"},
{StoreName:"MADU.HUTA ",StoreCategory:"Minimarket",StoreAddress:"Jl. Raya Penolih, Penolih Lor, Penolih, Kaligondang, Kabupaten Purbalingga, Jawa Tengah 53391, Indonesia"},
{StoreName:"NR foods",StoreCategory:"Food and Beverages",StoreAddress:"Jl. Pinayungan No.3, Telukjambe, Kec. Telukjambe Tim., Kabupaten Karawang, Jawa Barat 41361, Indonesia"},
{StoreName:"Toko Snack Bundatwin",StoreCategory:"Food and Beverages",StoreAddress:"Ruko Cluster Syariah Nakhiil Garden Pawarengan, Cikampek Bar., Kec. Cikampek, Kabupaten Karawang, Jawa Barat 41373, Indonesia"},
{StoreName:"warung sayur buah mamamel",StoreCategory:"Food and Beverages",StoreAddress:"Jl. H. Naimun No.32A, RT.2/RW.11, Pd. Pinang, Kec. Kby. Lama, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12310, Indonesia"},
{StoreName:"kepiting Brebes",StoreCategory:"Food and Beverages",StoreAddress:"Gg. Masjid Al Marzuq, Ps. Batang, Kec. Brebes, Kabupaten Brebes, Jawa Tengah 52211, Indonesia"},
{StoreName:"Meubel Bintaro Jaya",StoreCategory:"Fashion and Accessories",StoreAddress:"Jl. Cakalang No.9, Bintaro, Kec. Ampenan, Kota Mataram, Nusa Tenggara Bar., Indonesia"},
{StoreName:"NISSY MART",StoreCategory:"Minimarket",StoreAddress:"Jl. Letjen Harun Sohar No.9, Kebun Bunga, Kec. Sukarami, Kota Palembang, Sumatera Selatan 30961, Indonesia"},
{StoreName:"BestQuit",StoreCategory:"Fashion and Accessories",StoreAddress:"Jl. Gotong Royong I No.29B, RT.5/RW.2, Ragunan, Kec. Ps. Minggu, Kota Jakarta Selatan, Daerah Khusus Ibukota Jakarta 12550"},
{StoreName:"optik mahameru",StoreCategory:"Fashion and Accessories",StoreAddress:"Jl. Jati Makmur Permai Permai/Antara No.50, RT.005/RW.019, Jatimakmur, Kec. Pondokgede, Kota Bks, Jawa Barat 17413, Indonesia"},
{StoreName:"ZOYA PONTIANAK",StoreCategory:"Fashion and Accessories",StoreAddress:"Gg. Nurcahaya No.53, Sungai Bangkong, Kec. Pontianak Kota, Kota Pontianak, Kalimantan Barat 78113, Indonesia"},
{StoreName:"AISHWA Mini Fruits & Cake ",StoreCategory:"Food and Beverages",StoreAddress:"Griya Asri Nusantara Blok J No.19, Tanjung, Kec. Lamongan, Kabupaten Lamongan, Jawa Timur 62218, Indonesia"},
{StoreName:"RADJA ACC",StoreCategory:"Fashion and Accessories",StoreAddress:"Perumtas 3 , blok D3 No.04 , warsah , grabagan Kec.wonoayu "},
{StoreName:"JS.ID",StoreCategory:"Beauty & Health",StoreAddress:"Perum griya santika Jl. Santika 5 blok f10, Kademangan, Kademangaran, Kec. Dukuhturi, Tegal, Jawa Tengah 52181, Indonesia"},
{StoreName:"Muhammadiyah Store",StoreCategory:"Fashion and Accessories",StoreAddress:"Gg. 20 No.15, Pekajangan Utara, Pekajangan, Kec. Kedungwuni, Pekalongan, Jawa Tengah 51173, Indonesia"},
{StoreName:"DINDA SKINCARE DISTRIBUTOR MANADO",StoreCategory:"Beauty & Health",StoreAddress:"Jl. P.Sulawesi No.113, Batu Kota, Kec. Malalayang, Kota Manado, Sulawesi Utara, Indonesia"},
{StoreName:"toko Bang aL",StoreCategory:"Minimarket",StoreAddress:"Jl. Permata, Dawuan, Kec. Tengah Tani, Cirebon, Jawa Barat 45153, Indonesia"},
{StoreName:"Best Brand Muslimku.com",StoreCategory:"Fashion and Accessories",StoreAddress:"Jl. Rimat Bakti, Sijono Barat, Sijono, Kec. Warungasem, Kabupaten Batang, Jawa Tengah 51252, Indonesia"},
{StoreName:"Agen Nasa Jakarta Pusat",StoreCategory:"Beauty & Health",StoreAddress:"jalan setiakawan VIII no.36 rt.012 Rw.07 kelurahan. Duri pulo Kecamatan. Gambir 10140, RT.7/RW.7, Duri Pulo, Kecamatan Gambir, Kota Jakarta Pusat, Daerah Khusus Ibukota Jakarta 10140, Indonesia"},
{StoreName:"Toko Arief A3 PopCorn",StoreCategory:"Minimarket",StoreAddress:"Jl. Tembok Gede Gg. III No.25, Bubutan, Kec. Bubutan, Kota SBY, Jawa Timur 60174, Indonesia"},
{StoreName:"Remaja.id",StoreCategory:"Fashion and Accessories",StoreAddress:"Jl. Nakula II, Pd. Bambu, Kec. Duren Sawit, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta, Indonesia"},
{StoreName:"Yunie Allshop",StoreCategory:"Fashion and Accessories",StoreAddress:"Jl. Mayor Kamari Sampurno No.12B/100C, Ditotrunan, Kec. Lumajang, Kabupaten Lumajang, Jawa Timur 67313, Indonesia"},
{StoreName:"Permata_shop",StoreCategory:"Fashion and Accessories",StoreAddress:"Blok Kolla Rt 04 Rw05, Kolla, Leces, Kec. Leces, Probolinggo, Jawa Timur 67273, Indonesia"},
{StoreName:"KINAFI_SHOP",StoreCategory:"Fashion and Accessories",StoreAddress:"Jl. Nahromi, Waringinsari, Langensari, Kota Banjar, Jawa Barat 46342, Indonesia"},
{StoreName:"Bakso Mercon Kabitha",StoreCategory:"Food and Beverages",StoreAddress:"warung ibu mariam. kp sumur rt.07 rw.010. kel. klender kec. duren, sawit. patokan. masuk gg gurame. 1MT. tikor. QWJ7+4X, Klender, Duren Sawit, Jakarta Timur, DKI Jakarta, RT.9/RW.10, Klender, Kec. Duren Sawit, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13470, Indonesia"},
{StoreName:"ABI FROZEN FOOD ",StoreCategory:"Food and Beverages",StoreAddress:"Jl. Kembar, Dawung, Olak Alen, Kec. Selorejo, Blitar, Jawa Timur 66192, Indonesia"},
{StoreName:"WASERDA KUBS",StoreCategory:"Minimarket",StoreAddress:"Jl. Sekolah No.130A, Meranti Pandak, Kec. Rumbai Pesisir, Kota Pekanbaru, Riau 28266, Indonesia"},
{StoreName:"Mcollectionshop",StoreCategory:"Fashion and Accessories",StoreAddress:"Jl. Pendidikan No.21, Sumberejo, Wonomulyo, Kabupaten Polewali Mandar, Sulawesi Barat 91352, Indonesia"},
{StoreName:"Qilghashop",StoreCategory:"Fashion and Accessories",StoreAddress:"Jl. Tanah Baru Raya No.12, RT.04/RW.11, Tanah Baru, Kec. Bogor Utara, Kota Bogor, Jawa Barat 16154, Indonesia"},
{StoreName:"Puri Taman Sekar Food",StoreCategory:"Food and Beverages",StoreAddress:"Puri Taman Sekar Food Jl. Letda I Dewa Rai Hadnyana Gg Walet XIII No. 8, Batubulan Kangin, Kec. Sukawati, Kabupaten Gianyar, Bali 80582, Indonesia"},
{StoreName:"Aulia Fashion Store",StoreCategory:"Fashion and Accessories",StoreAddress:"Desa Gondel Kec. Kedungtuban Kab. Blora"},
{StoreName:"sweetcare_storepnk",StoreCategory:"Beauty & Health",StoreAddress:"Kab kuburaya kec sungai raya, Jl wonodadi 1 Gg podorukun 4"},
{StoreName:"TOKO CMS",StoreCategory:"Food and Beverages",StoreAddress:"Jl. Sukadanau No.124, Danau Indah, Kec. Cikarang Bar., Bekasi, Jawa Barat 17530, Indonesia"},
{StoreName:"warkop wulan (cabang kE-2) ",StoreCategory:"Food and Beverages",StoreAddress:"1, Jl. Ciliwung No.45, RT.9/RW.3, Kp. Melayu, Kecamatan Jatinegara, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13330, Indonesia"},
{StoreName:"Tasty Yoghurt",StoreCategory:"Food and Beverages",StoreAddress:"Griya Asri Light Cipageran, blok j 15, Jl. Kolonel Masturi, Cipageran, North Cimahi, Cimahi City, West Java 40511, Indonesia"},
{StoreName:"Kedai Tamansari - Online Store",StoreCategory:"Food and Beverages",StoreAddress:"Jl. Ciapus Raya No.21, RT.5/RW.2, Sukamantri, Kec. Tamansari, Bogor, Jawa Barat 16610, Indonesia"},
{StoreName:"jajananku frozen",StoreCategory:"Food and Beverages",StoreAddress:"Gg. H. Sirun No.29, RT.5/RW.1, Cakung Tim., Kec. Cakung, Kota Jakarta Timur, Daerah Khusus Ibukota Jakarta 13910, Indonesia"},
{StoreName:"Ghaudy",StoreCategory:"Fashion and Accessories",StoreAddress:"tanah abang gedung blok b"},
{StoreName:"Toko Eky",StoreCategory:"Food and Beverages",StoreAddress:"perumahan margahayu jaya Jl. tanjung V blok D no. 393 margahayu jaya bekasi timur"},
{StoreName:"Melsandy89's Store",StoreCategory:"Minimarket",StoreAddress:"Perumahan Pesona Ancaran Blok C.58,  Kec. Kuningan, Kabupaten Kuningan, Jawa Barat 45514, Indonesia"},
{StoreName:"AKU Shop",StoreCategory:"Minimarket",StoreAddress:"Unnamed Road, Bendotretek, Kec. Prambon, Kabupaten Sidoarjo, Jawa Timur 61265, Indonesia"},
{StoreName:"Atsshop",StoreCategory:"Fashion and Accessories",StoreAddress:"Jl. Raya Kopen, Kenteng, Madukara, Banjarnegara, Jawa Tengah 53482, Indonesia"},
{StoreName:"Naminasnack",StoreCategory:"Food and Beverages",StoreAddress:"Jl. Candrawulan II No.11, Turangga, Kec. Lengkong, Kota Bandung, Jawa Barat 40264, Indonesia"},
{StoreName:"EXPRESS & FAST OLSHOP",StoreCategory:"Fashion and Accessories",StoreAddress:"OLSHOP Center dengan pembayaran COD"},
{StoreName:"warung berca onlain",StoreCategory:"Minimarket",StoreAddress:"komplek pasar Meteseh, Kec. Tembalang, Kota Semarang, Jawa Tengah 50271, Indonesia"},
{StoreName:"Nizam23",StoreCategory:"Food and Beverages",StoreAddress:"Unnamed Road, Cimanggu, Langkaplancar, Pangandaran, Jawa Barat 46391, Indonesia"},
{StoreName:"Official Pelangi Store Khusus Mitra",StoreCategory:"Food and Beverages",StoreAddress:"Unnamed Road, Satriajaya, Kec. Tambun Utara, Bekasi, Jawa Barat 17510, Indonesia"},
{StoreName:"Gerai Jajanan Kinara",StoreCategory:"Food and Beverages",StoreAddress:"Jl. Simpei Karuhei, Palangka, Kec. Jekan Raya, Kota Palangka Raya, Kalimantan Tengah 74874, Indonesia"},
{StoreName:"Produk Herbal Kesehatan dan Kecantikan (Santi HWI)",StoreCategory:"Beauty & Health",StoreAddress:"Jl. Ikan Parang GG Bhinneka Tunggal Ika Kel.Rantau Panjang  Kec. Rumbai, Kota Pekanbaru, Riau 28264, Indonesia"},
{StoreName:"Chenille Collection",StoreCategory:"Fashion and Accessories",StoreAddress:"Jl. Raden Patah No.41, RT.001/RW.006, Parung Serab, Kec. Ciledug, Kota Tangerang, Banten 15153, Indonesia"},
{StoreName:"HIJAB STYLE JEPARA",StoreCategory:"Fashion and Accessories",StoreAddress:"gidangelo RT 4 RW 2 welahan Jepara"},
{StoreName:"intenbeautycareï¿½ï¿½",StoreCategory:"Beauty & Health",StoreAddress:""},
{StoreName:"Novilla Shop",StoreCategory:"Fashion and Accessories",StoreAddress:"Jl Kalimalang RT.004/RW.002 NO:285 Kelurahan Jatimulya Tambun Selatan Bekasi"},
{StoreName:"kesehatan",StoreCategory:"Beauty & Health",StoreAddress:"Unnamed Road, Wonorejo Lor, Tuban, Kec. Gondangrejo, Kabupaten Karanganyar, Jawa Tengah 57188, Indonesia"},
{StoreName:"pasar 21",StoreCategory:"Food and Beverages",StoreAddress:"Dumai, Kota Dumai, Riau, Indonesia"},
{StoreName:"Meat & Chick",StoreCategory:"Minimarket",StoreAddress:"Jl. Mulawarman Raya Ruko No 11D Pedalangan, Kec. Banyumanik, Kota Semarang, Jawa Tengah, Indonesia"},
{StoreName:"dechibishop",StoreCategory:"Fashion and Accessories",StoreAddress:"Jl. Kwaron 2, Bangetayu Kulon, Kec. Genuk, Kota Semarang, Jawa Tengah 50115, Indonesia"},
{StoreName:"skincarebeautys",StoreCategory:"Beauty & Health",StoreAddress:"bandung"},
 ]
  res.send({'data':data})
})

// get manual location

app.get('/getCity', (req, res) => {

    const City = 
        [
            {Name:"Yogyakarta"},
            {Name:"Jakarta"},
            {Name:"Dumai"},
            {Name:"Makassar"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Bandung"},
            {Name:"Palembang"},
            {Name:"Medan"},
            {Name:"Bekasi"},
            {Name:"Jakarta"},
            {Name:"Bekasi"},
            {Name:"Jakarta"},
            {Name:"Bandung"},
            {Name:"Surabaya"},
            {Name:"Surabaya"},
            {Name:"Jakarta"},
            {Name:"Semarang"},
            {Name:"Batam"},
            {Name:"Tasikmalaya"},
            {Name:"Semarang"},
            {Name:"Surabaya"},
            {Name:"Bandung"},
            {Name:"Palembang"},
            {Name:"Palembang"},
            {Name:"Surabaya"},
            {Name:"Palu"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Yogyakarta"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Bandung"},
            {Name:"Surabaya"},
            {Name:"Palembang"},
            {Name:"Jakarta"},
            {Name:"Surabaya"},
            {Name:"Surabaya"},
            {Name:"Semarang"},
            {Name:"Jakarta"},
            {Name:"Cirebon"},
            {Name:"Surabaya"},
            {Name:"Cirebon"},
            {Name:"Semarang"},
            {Name:"Makassar"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Surabaya"},
            {Name:"Palu"},
            {Name:"Bekasi"},
            {Name:"Makassar"},
            {Name:"Magelang"},
            {Name:"Jakarta"},
            {Name:"Surabaya"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Surabaya"},
            {Name:"Jakarta"},
            {Name:"Surabaya"},
            {Name:"Palembang"},
            {Name:"Medan"},
            {Name:"Bekasi"},
            {Name:"Pontianak"},
            {Name:"Surabaya"},
            {Name:"Surabaya"},
            {Name:"Tangerang"},
            {Name:"Jakarta"},
            {Name:"Semarang"},
            {Name:"Surabaya"},
            {Name:"Makassar"},
            {Name:"Bandung"},
            {Name:"Semarang"},
            {Name:"Jakarta"},
            {Name:"Surabaya"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Surabaya"},
            {Name:"Surabaya"},
            {Name:"Bandung"},
            {Name:"Jakarta"},
            {Name:"Kediri"},
            {Name:"Medan"},
            {Name:"Palu"},
            {Name:"Bogor"},
            {Name:"Denpasar"},
            {Name:"Semarang"},
            {Name:"Banjarmasin"},
            {Name:"Bekasi"},
            {Name:"Jakarta"},
            {Name:"Bandung"},
            {Name:"Bogor"},
            {Name:"Jakarta"},
            {Name:"Banjarmasin"},
            {Name:"Bekasi"},
            {Name:"Tasikmalaya"},
            {Name:"Surabaya"},
            {Name:"Magelang"},
            {Name:"Makassar"},
            {Name:"Makassar"},
            {Name:"Bandung"},
            {Name:"Surabaya"},
            {Name:"Semarang"},
            {Name:"Bandung"},
            {Name:"Surabaya"},
            {Name:"Bekasi"},
            {Name:"Banjarmasin"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Semarang"},
            {Name:"Bandung"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Medan"},
            {Name:"Semarang"},
            {Name:"Surabaya"},
            {Name:"Cirebon"},
            {Name:"Manado"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Bukittinggi"},
            {Name:"Bogor"},
            {Name:"Bandung"},
            {Name:"Semarang"},
            {Name:"Jakarta"},
            {Name:"Kediri"},
            {Name:"Jakarta"},
            {Name:"Batam"},
            {Name:"Batam"},
            {Name:"Jakarta"},
            {Name:"Palu"},
            {Name:"Bogor"},
            {Name:"Surabaya"},
            {Name:"Surabaya"},
            {Name:"Surabaya"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Banjarmasin"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Bandung"},
            {Name:"Bandar Lampung"},
            {Name:"Padang"},
            {Name:"Bandung"},
            {Name:"Jakarta"},
            {Name:"Medan"},
            {Name:"Surabaya"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Surabaya"},
            {Name:"Medan"},
            {Name:"Jakarta"},
            {Name:"Bandung"},
            {Name:"Depok"},
            {Name:"Yogyakarta"},
            {Name:"Kediri"},
            {Name:"Padang"},
            {Name:"Surabaya"},
            {Name:"Jakarta"},
            {Name:"Bandung"},
            {Name:"Banjarmasin"},
            {Name:"Surabaya"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Bandung"},
            {Name:"Medan"},
            {Name:"Surabaya"},
            {Name:"Jakarta"},
            {Name:"Bekasi"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Pontianak"},
            {Name:"Bandung"},
            {Name:"Semarang"},
            {Name:"Jakarta"},
            {Name:"Surabaya"},
            {Name:"Batam"},
            {Name:"Surabaya"},
            {Name:"Jakarta"},
            {Name:"Bengkulu"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Tangerang"},
            {Name:"Makassar"},
            {Name:"Yogyakarta"},
            {Name:"Magelang"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Mataram"},
            {Name:"Surabaya"},
            {Name:"Surabaya"},
            {Name:"Surabaya"},
            {Name:"Bukittinggi"},
            {Name:"Makassar"},
            {Name:"Jayapura"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Medan"},
            {Name:"Banjarmasin"},
            {Name:"Jakarta"},
            {Name:"Surabaya"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Medan"},
            {Name:"Surabaya"},
            {Name:"Bandung"},
            {Name:"Kediri"},
            {Name:"Semarang"},
            {Name:"Semarang"},
            {Name:"Medan"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Palembang"},
            {Name:"Denpasar"},
            {Name:"Surabaya"},
            {Name:"Tangerang"},
            {Name:"Makassar"},
            {Name:"Jakarta"},
            {Name:"Palu"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Makassar"},
            {Name:"Surabaya"},
            {Name:"Jakarta"},
            {Name:"Yogyakarta"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Medan"},
            {Name:"Denpasar"},
            {Name:"Medan"},
            {Name:"Yogyakarta"},
            {Name:"Yogyakarta"},
            {Name:"Yogyakarta"},
            {Name:"Semarang"},
            {Name:"Malang"},
            {Name:"Medan"},
            {Name:"Surabaya"},
            {Name:"Semarang"},
            {Name:"Surabaya"},
            {Name:"Bandung"},
            {Name:"Tangerang"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Palembang"},
            {Name:"Bandung"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Jakarta"},
            {Name:"Surabaya"},
            {Name:"Surakarta"},
            {Name:"Jakarta"},
            {Name:"Surabaya"},
            {Name:"Bogor"},
            {Name:"Tasikmalaya"},
            {Name:"Surabaya"},
            {Name:"Surabaya"},
            {Name:"Pontianak"},
            {Name:"Jakarta"},
            {Name:"Tangerang"},
            {Name:"Surabaya"},
            {Name:"Denpasar"},
            {Name:"Surabaya"},
            {Name:"Surabaya"},
            {Name:"Surabaya"},
            {Name:"Surabaya"},
            {Name:"Jakarta"},
            {Name:"Medan"},
            {Name:"Jakarta"},
            {Name:"Blitar"},
            {Name:"Jakarta"},
            {Name:"Banjarmasin"},
            {Name:"Bandung" },

        ]
      res.send({'City':City})
    })
        


//get store category

app.get('/getCategory', (req, res) => {

    Category =[
        {
        CategoryName:"Food and Beverages",
        CategoryImage:"xyz.png"
    },
    {
        CategoryName:"Fashion and Accessories",
        CategoryImage:"xyz.png"
    },
    {
        CategoryName:"Minimarket",
        CategoryImage:"xyz.png"
    },
    {
        CategoryName:"Beauty & Health",
        CategoryImage:"xyz.png"
    },
    {
        CategoryName:"Food and Beverages",
        CategoryImage:"xyz.png"
    },
    {
        CategoryName:"Food and Beverages",
        CategoryImage:"xyz.png"
    },
  
]


    res.send({'Category':Category})


})




app.listen(port, () => {
  console.log(`Example app listening at http://localhost:${port}`)
})